### PR TITLE
document func event.Timeout

### LINKED ISSUE #226: Add documentation for event.Timeout
```
event/event.gen.go:1138:1: comment on exported function Timeout should be of the form "Timeout ..." (golint)
// (no documentation)
^
```

### PR DESCRIPTION
**Pull request by ilmanzo**
fix #226

### CODE REVIEW

**Comment by pdf** [comment]
This file is generated, so I think this would need to be overridden somehow in the generator.

**Comment by ilmanzo** [comment]
I see... But running the generator, I get a file without any func definition. Maybe reference page has changed, or parsing is broken ?

```
//go:generate go run generate.go

// Package event defines markup to bind DOM events.
//
// Generated from "Event reference" by Mozilla Contributors,
// https://developer.mozilla.org/en-US/docs/Web/Events, licensed under
// CC-BY-SA 2.5.
package event

import "github.com/gopherjs/vecty"

```

**Comment by slimsag** [comment]
Yeah, the generator is broken at this point due to MDN changes, that doesn't surprise me.

I think making this a hand-written file for now, until we have a better generator source (i.e. https://github.com/gopherjs/vecty/issues/136) is fine. That way we can continue to improve the package and once we do have a better generator, we can use the existing packages as test cases effectively.

**Comment by slimsag** [comment]
@ilmanzo I'd like to merge this as-is, not sure why you closed the PR? Would you be willing to re-send it?

**Comment by ilmanzo** [comment]
Sorry, I understood you were fixing the generator... NP I'll reopen it

**Pull request merged**
