### PR TITLE
handle nil *HTML in render

### PR DESCRIPTION
**Pull request by slimsag**
This change fixes a regression introduced by PR #134.

The basic issue is that when `nil` is encountered, it is treated correctly as a nil render,
but when `(*HTML)(nil)` is encountered, it is not. I discovered this while porting
Go-Package-Store (which uses Vecty) over to the new API.

The following code effectively demonstrates the issue:

```Go
package main

import (
	"github.com/gopherjs/vecty"
	"github.com/gopherjs/vecty/elem"
)

func main() {
	vecty.RenderBody(&PageView{})
}

type PageView struct {
	vecty.Core
}

func (p *PageView) Render() *vecty.HTML {
	return elem.Body(
		// this works:
		//nil,

		// this does not:
		p.returnsNil(),
	)
}

func (p *PageView) returnsNil() *vecty.HTML {
	return nil
}
```

### CODE REVIEW

**Comment by slimsag** [comment]
@pdf

**Comment by pdf** [comment]
What about adding a `nil` check inside the case at https://github.com/gopherjs/vecty/blob/8eca1d5d9a4612f21920781987b0c58155969ac8/markup.go#L64?

**Comment by slimsag** [comment]
Yes, that works as well. Does the latest commit look good to you? If so I'll squash merge

**Comment by pdf** [comment]
I'd add it to the compound case, then it handles a `nil` `Component` or `List` return value too.

**Comment by slimsag** [comment]
- `nil` obviously would not change, it'd still be `nil`.
- `(List)(nil)` should already be handled elsewhere where we interact with `List`, via `range` etc.
- `Component` is an `interface` and as such can't run into this problem. For example https://play.golang.org/p/SSg2vbLLk8 

So the only question is about readability of the code, I think?

**Comment by slimsag** [comment]
(I confirmed changing the `returnsNil` return type in PR description example code to `Component` and `List` also works just fine with the code as-is)

**Comment by pdf** [comment]
You are indeed correct, LGTM then.

**Pull request merged**
