### PR TITLE
Documentation and Tutorial updates

### PR DESCRIPTION
**Pull request by anxiousmodernman**
Add updates to README.md, and a simple hello world example.

Also add a docs folder, where we can collect long-form documentation. This will be
subject to change as the API evolves.

### CODE REVIEW

**Comment by anxiousmodernman** [comment]
I intend to squash these down after discussion or approval. I think it would be helpful to have something a little bit "official" around contributions and project structure. We might want to adopt/link to something from gopherjs.

Having contribution guidelines documented will make it easier for maintainers. I have a boilerplate one here https://gist.github.com/anxiousmodernman/0ef4bb8441a3771a57bd3cc7b5b497b4 but since this is being developed under gopherjs we might want @shurcooL input.

**Comment by slimsag** [comment]
Hi @anxiousmodernman ! I won't have time to review this in-depth for at least 1 week, apologies ahead of time. A couple of high level comments right off the bat:

- Any PR for docs should be made against the [`docfest` branch](https://github.com/gopherjs/vecty/tree/docfest), please. The reason this is not being done on `master` is because documentation cannot be fully written until at least 1.0 (https://github.com/gopherjs/vecty/milestone/1) which is some ways off. Additionally, I would like to keep docs hidden from the general public for the time being until I do feel Vecty is in a 1.0 state / ready for broad adoption.

I'll have further comments later, I am sure, but in general I would like to say that documentation is the one thing I think Vecty must absolutely do right. This means it needs to be reviewed and revised extensively, which makes PRs a hard format to work in, I think, due to the latency between me and you. Regardless, as long as that doesn't bother you I'm glad to have such contributions :) For the sake of making such PRs less long-winded, could we edit only one documentation file per PR? I think that would help.

**Comment by slimsag** [comment]
>  I think it would be helpful to have something a little bit "official" around contributions and project structure.

Can you elaborate on what, specifically, you would've liked to find in such a document? My personal preference lies towards such documents being a waste of time / resources because they typically only cover things that are obvious; and for things that are not so obvious the document typically can't describe them in an easy way / they have to be described via direct communication anyway.

**Comment by anxiousmodernman** [comment]
I will close this and reopen against `docfest` later. I see in that branch you also have a **docs** folder  with markdown inside.

Regarding the second point, many projects have a **CONTRIBUTING.md** file in their root. This is a loose convention that [GitHub endorses with some light tooling](https://github.com/blog/1184-contributing-guidelines). Examples of things you can do there:

* Guidelines on naming git branches
* Commit style, squash vs no-squash
* Code Style guides, or a link to a common one like Golange Code Comments
* Outline of project structure (where code lives, how to build, how to run tests, where docs live)
* How to file bugs

People will usually end up reaching out directly. But if you, as the maintainer, need to take a hard line to protect the quality of the project, having a doc to reference can be helpful.

I'll close this for now in favor of discussion on slack or in issue #31

**Pull request closed without merging**
