### PR TITLE
Implement Mounter, trigger mount/unmount based on component equality

### PR DESCRIPTION
**Pull request by pdf**
I realize #75 and #85 were split out, but the implementation is really intrinsically linked.  Since the issues appear to be stagnating somewhat, I thought I'd submit a PR to see if we can get some forward-progress here.

### CODE REVIEW

**Comment by slimsag** [comment]
Thanks for sending this, and sorry I haven't had a chance to give it my full attention yet.

I'm concerned about the complexity of `doMountUnmount`, and the fact that it uses reflection. I think I need to consider more heavily in which situations users will need/want component mount and unmount events in the general case. One immediate question might be: Will normal users (not interacting with JS) want Mount to be a separate function than their component constructor `NewMyComponent`?

I'll delve into this further later. Sorry for the delays, again!

**Comment by pdf** [comment]
I understand the lack of time, no worries.

The complexity in `doMountUnmount` is at least as much about correcting `Unmount` behaviour as it is about enabling mounting.  As it stands, `Unmount` is broken any time the number of siblings changes, which can lead to leaking handles and other unexpected behaviour in user code.  The added complexity to support `Mount` is actually pretty low, if you consider that most of the code is required to make `Unmount` work.

I really do hope you'll consider JS/DOM interaction a valid use-case (I suspect this may be a moderately regular hurdle), though I think it'd still be worthwhile simply for API consistency.  It also supports component re-use.

I'm currently building against my fork and using Mount/Unmount to manage JS/DOM interactions, as well as Store subscribe/unsubscribe.

**Comment by slimsag** [comment]
> I really do hope you'll consider JS/DOM interaction a valid use-case (I suspect this may be a moderately regular hurdle), though I think it'd still be worthwhile simply for API consistency. It also supports component re-use.

FWIW I absolutely do consider that a valid use case. But I think these users will need very extensive integration, far more than what is provided here with simple Mount/Unmount. My theory is that we could allow these users to integrate via a `js` API directly, and reserve the Go Vecty API here for users who are not attempting JS/DOM interaction directly.

**Comment by pdf** [comment]
I've updated this to treat component inequality as a mount/unmount trigger, rather than type equality as otherwise references to a component that leak to the outside world from the mount hook can lead to unexpected behaviour if the component is replaced with a new instance.  Combined with #94 though, additional mount/unmount events can be avoided by using a single reference to a component across renders.

**Comment by pdf** [comment]
Closing in favour of #107 meta-pull.

**Pull request closed without merging**
